export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
	return (
		<html lang='fa' dir="rtl">
			<body style={{height:"100vh" , width: "100vw" , margin:"0"}}>{children}</body>
		</html>
	);
}
